### ISSUE TITLE
Navbar component fails Jest test because of imported Node module svelte component

### ISSUE THREAD

**Issue by deuch13** [dusk-network/dusk-ui-kit#202]
**Describe the bug**
The navbar component is failing the render Jest test because a child component ( 'A11yMenu' ) is importing a svelte file from a node module ( "import DarkMode from 'svelte-dark-mode' ")

**To Reproduce**
Run `pnpm jest` for the dusk-ui-kit

```
// Be exhsustive
//
```

**Expected behaviour**
The Navbar component should pass it's render component test

**Logs/Screenshot**
![err-log](https://user-images.githubusercontent.com/28288533/137280781-846d6466-8267-4ff2-b213-a2a20ba3db19.PNG)

**Platform**
Fill as appropriate

- Architecture: [ARM, 8086]
- OS: [e.g. iOS, Linux]
- Browser [e.g. chrome, safari

**Additional context**
Ways that were researched but with no positive results:
- Adding the module to Jests config transformIgnorePatterns property 
- Mocking the module with Jests `Jest.mock()` 
- Creating a mock file for Jest to use

The issues appears to stem from the way Jest resolves the import of the DarkMode module, not sure if it's being transpilied before jest runs the test.
If the DarkMode.svelte file is moved from node_modules inside the component folder the test passes, but requires a mock file for `mediaMatch()`

**Comment by kieranhall** [comment]
This test is currently disabled, right?

**Comment by deuch13** [comment]
Yes, the test is currently disabled.

**Comment by kieranhall** [comment]
Closing this in favour of opening a ticket to tackle the test directly.
