### ISSUE TITLE
Update UI Kit component styles

### ISSUE THREAD

**Issue by deuch13** [dusk-network/dusk-ui-kit#257]

**Comment by kieranhall** [comment]
What's this issue about @deuch13?

**Comment by deuch13** [comment]
Some UI Kit components need minor updates done to their styles so they display correctly with other components.
e.g SearchList needs its `container` class removed.
Created this issue so i can address all such matters instead of opening an issue for every minor issue that is found.

**Comment by kieranhall** [comment]
ok, thanks for clarifying 👍
