### ISSUE TITLE
[docs] [nav] FileUpload breaking app navigation in documentation

### ISSUE THREAD

**Issue by sanderdms** [dusk-network/dusk-ui-kit#265]
**Describe the bug**
In the documentation the _FileUpload_ example is triggering uncaught errors upon clicking the _Upload_ button. Whereafter the application navigation  no longer works as expected. The URL updates, but view remains the same.
Workaround is to manually refresh the page.

**To Reproduce**
- Goto UI Kit documentation
- Navigate to MOLECULES
- Navigate to file-upload package
- Click on the _Upload_ Button in _Example 1_
- Navigate to HELPERS via main menu

**Expected behaviour**
Land on the HELPERS page after clicking HELPERS in the main menu. 

**Platform**
- OS: MacOS
- Browser: Chrome 95.0.4638.69 (x86_64)

**Comment by kieranhall** [comment]
I'll push in a fix for this next week.

**Comment by kieranhall** [comment]
Closed in error... This one will be getting a fix pushed in soon.

**Comment by kieranhall** [comment]
This is now fixed.
