### ISSUE TITLE
[design language] [interaction] unconventional use of cursor row-resize

### ISSUE THREAD

**Issue by sanderdms** [dusk-network/dusk-ui-kit#273]
Cursor _row-resize_ is being used on both _[accordion](https://dusk-network.github.io/dusk-ui-kit/storybook/?path=/story/components-organisms-accordion--standard-accordion)_ and _[kitchen sink table](https://dusk-network.github.io/dusk-ui-kit/storybook/?path=/story/components-organisms-table--kitchen-sink-example)_.  What is the philosophy behind this use and under what conditions should this style be considered when creating new components for the design system ?

Are we aware this is a rather unconventional use for this cursor style ?

**Comment by kieranhall** [comment]
Hi @sanderdms, thanks for the question.  The cursor has been used here to indicate that the item/row can be resized vertically.

We're aware that it's recycling this cursor that is more commonly used for drag events, but feel it offers another visual cue to the fact that there is more information to be revealed.  This should be the same for all components that have hidden content that expands into a horizontal row.

I will add your feedback to a scheduled meeting that will cover this topic.
