### ISSUE TITLE
When hovering there is no data displayed 

### ISSUE THREAD

**Issue by sophielouisefeith** [dusk-network/dusk-ui-kit#509]
**Describe the bug**
When hovering over the icon's there is not data displayed 
<img width="706" alt="Screenshot 2022-03-14 at 15 33 08" src="https://user-images.githubusercontent.com/57356744/158193993-bf212332-9fac-4fc1-a368-af922244c1c8.png">

**To Reproduce**
go to https://dusk-explorer-preprod-p8982.ondigitalocean.app/blocks/ hover over the icon

**Comment by kieranhall** [comment]
This is at medium screen sizes.
