### ISSUE TITLE
Change the arrow

### ISSUE THREAD

**Issue by sophielouisefeith** [dusk-network/dusk-ui-kit#521]
The arrows needs to be changed, they're semantically wrong. We're currently using the "backspace" (the "x" indicates the deleting action, where the arrow indicate the direction). This is the same icon users find on their keyboards but used for a totally different meaning, therefore is breaking two / three different design heuristics.

As a note: in the future we should also avoid the paging for such things: users will never jump from a page to another, but it will load progressively more results if they need to. Therefore the correct UI here would be either a "Load more" or a "Progressive loading" when the user scrolls.

![image](https://user-images.githubusercontent.com/57356744/158383861-dfb77ae1-4b63-4f4b-b874-a9570bd837cd.png)

**Comment by kieranhall** [comment]
`arrow-circle-left` and `arrow-circle-right` should be a good replacement option.
