### ISSUE TITLE
Create a MessageBanner component

### ISSUE THREAD

**Issue by kieranhall** [dusk-network/dusk-ui-kit#625]
**Describe what you want implemented**
A banner that spans 100% of the page.

**Describe "Why" this is needed**
Needed to announce messages to our users.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by kieranhall** [comment]
@laremas FYI

**Comment by laremas** [comment]
check the [Component here](https://www.figma.com/file/GClxuixHvofhGl3zxGlZdT/Dusk-Ui-Kit-(wip-update)?node-id=3389%3A26889 )
