### ISSUE TITLE
Add cms-connector models and schemas in published UI Kit

### ISSUE THREAD

**Issue by kieranhall** [dusk-network/dusk-ui-kit#719]
**Describe what you want implemented**
The models and schemas that are generated and maintained in the `cms-connector` repository are to be published with the UI Kit packages.  This can be achieved by removing the `private` property from the package.json.

The `uikit-schemas` directory should also be renamed to `schemas`.

**Describe "Why" this is needed**
So that the CMS can depend on these files via NPM, and be automatically integrated there when we publish new UI Kit versions.

**Comment by mean2me** [comment]
Done here: https://github.com/dusk-network/dusk-ui-kit/actions/runs/3203620443
