### ISSUE TITLE
Loader when chain info is not fetched yet

### ISSUE THREAD

**Issue by volta-vianney** [dusk-network/dusk-ui-kit#845]
Hi,

I've installed the explorer pwa on my phone (galaxy s9 android).

In the chain Info tab when we click there is only the market data available. So I was refreshing the page a lot to get all the info about the provisioners etc...
Then I understood maybe the chain info is not available right away and need to be fetched. This would take more time than the market data.

If this is what prevents the display of all the chain info in this tab, I think from a UI perspective, it would be nice to have a loader or a feedback for the user that the info is not ready to be displayed.

**Comment by deuch13** [comment]
Issue is not related to the UI Kit and does not follow any issue template that are agreed.
